### PR TITLE
Create github pipeline and update migrations 

### PR DESCRIPTION
**Pull request by ZabGo**
**Github Actions**
This PR adds github actions to run tests on every PR that will be merged into the main branch. In the future we will be able to add more tools such SCA, linter, etc.
The pipeline is running but the tests are failing. Let me know if you want us to look into the tests before merging this PR. Otherwise we can create another PR to fix the tests that are failing.

**Update migration files**
I modified and deleted some migration files so that we can  insert the cards on an empty database. @tobyirvine let me know what you think. Any feedback welcome :-)

### CODE REVIEW

**Comment by sydseter** [comment]
I think it makes sense to look at the tests as well. otherwise, it's not given that the pipeline will look like this.

**Comment by sydseter** [comment]
You should also ensure your commits are verified. https://docs.github.com/en/authentication/managing-commit-signature-verification I know it's you, but, it's good to be certain that nobody else have sneaked something in there that looks like you.

**Comment by ZabGo** [comment]
> You should also ensure your commits are verified. https://docs.github.com/en/authentication/managing-commit-signature-verification I know it's you, but, it's good to be certain that nobody else have sneaked something in there that looks like you.

I'll have a look at this. Thanks :-)

**Comment by ZabGo** [comment]
> I think it makes sense to look at the tests as well. otherwise, it's not given that the pipeline will look like this.

Yes it's just a starting point. We'll add other jobs and other workflows or change it completely.

**Comment by tobyirvine** [comment]
Thanks @ZabGo! I see now how I broke the migrations for new databases when I added the new external_card_id column back in 2022. The card data population should have been a part of the migrations from the start, not separate in the seeds.

Just a few tidy-ups:

- I appreciate it’s just an ephemeral test database instance, but I’ve created a secret in the repository called POSTGRES_TEST_PWD. Can you update the workflow yaml to set the ENV variable from there and the Elixir test conf to read from it?
- I think copi.iml is an IntelliJ file that leaks out of the .idea directory. Can you remove it and update .gitignore to prevent it from coming back?
- Can you restore priv/repo/migrations/20221014193927_index_external_card_ids.exs? Elixir keeps track of the run migrations in the database, and it will get very confused in production if one is missing.

**Comment by ZabGo** [comment]
> Thanks @ZabGo! I see now how I broke the migrations for new databases when I added the new external_card_id column back in 2022. The card data population should have been a part of the migrations from the start, not separate in the seeds.
> 
> Just a few tidy-ups:
> 
> * I appreciate it’s just an ephemeral test database instance, but I’ve created a secret in the repository called POSTGRES_TEST_PWD. Can you update the workflow yaml to set the ENV variable from there and the Elixir test conf to read from it?
> * I think copi.iml is an IntelliJ file that leaks out of the .idea directory. Can you remove it and update .gitignore to prevent it from coming back?
> * Can you restore priv/repo/migrations/20221014193927_index_external_card_ids.exs? Elixir keeps track of the run migrations in the database, and it will get very confused in production if one is missing.

Hi @tobyirvine, I tidied up the PR. Let me know if you are happy to merge it. :-)

**Pull request merged**
